version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha:
        applies-to: version-updates
        patterns:
        - "*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gradle:
        applies-to: version-updates
        patterns:
        - '*'
