version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha:
        applies-to: version-updates
        patterns:
        - "*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle:
        applies-to: version-updates
        patterns:
        - "*"
    ignore:
      - dependency-name: "io.netty:*"
      - dependency-name: "org.bouncycastle:*"
      - dependency-name: "com.aayushatharva.brotli4j:*"
      - dependency-name: "org.apache.httpcomponents.client5:httpclient5"
      - dependency-name: "org.jitsi:ice4j"
