name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency: 
  group:  ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17, 19]
        include:
          - os: windows-latest
            java: 17
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            wdm
      - run: ./gradlew "-Dorg.gradle.jvmargs=-Xmx4g" assemble
        env:
          WDM_CACHEPATH: "~/.gradle/wdm"
      - run: ./gradlew check
