name: CI Remote

on:
  workflow_dispatch:
  schedule:
    # Once a month
    - cron:  '0 8 18 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            wdm
      - run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4g --continue --no-parallel test
        env:
          ZAP_REMOTE_TESTS: 1
